spring:
  application:
    name: hello-spring-cloud-eureka

server:
  port: 7003

eureka:
  instance:
    hostname: locahost     # eureka服务端的实力名称
  client:
    fetch-registry: false  # false表示自己就是注册中心。我的职责就是维护服务实例，并不需要去检索服务
    register-with-eureka: false   # false表示自己不需要向注册中心注册自己
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/