spring:
  application:
    name: hello-spring-cloud-service-redis
  boot:
    admin:
      client:
        url: http://localhost:8084
  zipkin:
    base-uri: http://localhost:9411
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
      sentinel:
        master: mymaster
        nodes: 192.168.150.141:26379,192.168.150.141:26380,192.168.150.141:26381

server:
  port: 7013

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7003/eureka/

management:
  endpoint:
    health:
      show-detials: always
  endpoints:
    web:
      exposure:
        include: health,info

