spring:
  application:
    name: hello-spring-cloud-service-admin

server:
  port: 7004
zipkin:
  base-uri: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7003/eureka/