spring:
  application:
    name: hello-spring-cloud-web-admin-ribbon

server:
  port: 7006
zipkin:
  base-uri: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7003/eureka/