spring:
  application:
    name: hello-spring-cloud-web-admin-feign

server:
  port: 7007

zipkin:
  base-uri: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7003/eureka/

feign:
  hystrix:
    enable: true
    command:
      default:
        execution:
          timeout:
            enable: fales  #解决超时问题（方案一：关闭请求时间限制）

