spring:
  application:
    name: hello-spring-cloud-zipkin

server:
  port: 7011

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7003/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false