spring:
  application:
    name: hello-spring-cloud-zipkin
  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7003/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false