spring:
  application:
    name: hello-spring-cloud-zuul

server:
  port: 7008

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7003/eureka/

zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: hello-spring-cloud-web-admin-feign
    api-b:
      path: /api/b/**
      serviceId: hello-spring-cloud-web-admin-ribbon